### PR TITLE
Added Scala 2.13 support.

### PR DESCRIPTION
**Pull request by eltherion**
Added Scala 2.13 support.

### CODE REVIEW

**Comment by eltherion** [comment]
@fiadliel Hi, it would be great to have that artifact published for 2.13.x. I'm also not hiding the fact that this dependency blocks one of my project towards 2.13 migration. 😛 Anyway, if you found a little bit of time to look at it, I would be very gratuitous.

**Comment by sullis** [comment]
ping @fiadliel

**Comment by emersonmoura** [comment]
Hi everyone. Why it isn't supported yet? I strongly believe there are more people who need it like me. @fiadliel?

**Comment by eltherion** [comment]
@emersonmoura  https://github.com/eltherion/http4s-timer/releases/tag/v0.1.13

2zo1ki

**Comment by emersonmoura** [comment]
LOL. Sorry I'm new here and I didn't find the merge log on this PR, also I didn't find the newest version of this code when I cloned this repository. Last but not least I didn't find the newest jar version at the Mvn repository, So I was a bit lost XD. Thank you @eltherion

**Pull request closed without merging**
